config/routes.rb
NewAuthDemo::Application.routes.draw do
  resources :users, :only => [:create, :new, :show]
  resource :session, :only => [:create, :destroy, :new]

  root :to => "static_pages#index"
  
  get '/about', to: 'static_pages#about', as: 'about'
  get '/contact', to: 'static_pages#contact', as: 'contact'
  get '/gallery', to: 'static_pages#gallery', as: 'gallery'
  get '/testimonials', to: 'static_pages#testimonials', as: 'testimonials'
  get '/', to: 'static_pages#index', as:'index'
  
end

app/models/user.rb
class User < ActiveRecord::Base
  attr_reader :password
  validates :password_digest, :presence => true
  validates :password, :length => { :minimum => 6, :allow_nil => true }
  validates :session_token, :presence => true, :uniqueness => true
  validates :username, :presence => true, :uniqueness => true

  before_validation :ensure_session_token

  def self.find_by_credentials(username, password)
    user = User.find_by_username(username)
    user.try(:is_password?, password) ? user : nil
  end

  def self.generate_session_token
    SecureRandom::urlsafe_base64(16)
  end

  def is_password?(unencrypted_password)
    BCrypt::Password.new(self.password_digest).is_password?(unencrypted_password)
  end

  def password=(unencrypted_password)
    if unencrypted_password.present?
      @password = unencrypted_password
      self.password_digest = BCrypt::Password.create(unencrypted_password)
    end
  end

  def reset_session_token!
    self.session_token = self.class.generate_session_token
    self.save!
    self.session_token
  end

  private

  def ensure_session_token
    self.session_token ||= self.class.generate_session_token
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  # Expose these methods to the views
  helper_method :current_user, :signed_in?

  private

  def current_user
    return nil unless session[:token]
    @current_user ||= User.find_by_session_token(session[:token])
  end

  def signed_in?
    !!current_user
  end

  def sign_in(user)
    @current_user = user
    session[:token] = user.reset_session_token!
  end

  def sign_out
    current_user.try(:reset_session_token!)
    session[:token] = nil
  end

  def require_signed_in!
    redirect_to new_session_url unless signed_in?
  end

  def require_signed_out!
    redirect_to user_url(current_user) if signed_in?
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  before_action :require_signed_out!, :only => [:new, :create]
  before_action :require_signed_in!, :only => [:destroy]

  def new
  end

  def create
    @user = User.find_by_credentials(
      user_params[:username],
      user_params[:password]
    )

    if @user
      sign_in(@user)
      redirect_to user_url(@user)
    else
      flash.now[:errors] = ["Invalid Credentials"]
      render :new
    end
  end

  def destroy
    sign_out
    redirect_to new_session_url
  end

  private

  def user_params
    params.require(:user).permit(:username, :password)
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :require_signed_in!, :only => [:show]
  before_action :require_signed_out!, :only => [:create, :new]

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      sign_in(@user)
      redirect_to user_url(@user)
    else
      flash.now[:errors] = @user.errors.full_messages
      render :new
    end
  end

  def show
    if params.include?(:id)
      @user = User.find(params[:id])
    else
      redirect_to user_url(current_user)
    end
  end

  private

  def user_params
    params.require(:user).permit(:username, :password)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <%= stylesheet_link_tag 'application' %>
    <%= javascript_include_tag 'application' %>
    <%= csrf_meta_tags %>
    <title>NewAuthDemo</title>
  </head>
  <body data-spy="scroll" data-target=".scroll-nav">
    <!-- Top-Level Navbar -->
    <nav class="navbar navbar-default" role="navigation">
      <div class="container-fluid">
        <div class="navbar-header">
          <button
            type="button"
            class="navbar-toggle collapsed"
            data-toggle="collapse"
            data-target="#nav-bar">
          <span class="sr-only">Toggle navigation</span>
                  <span class="icon-bar"></span>
                  <span class="icon-bar"></span>
                  <span class="icon-bar"></span>
          </button>
          <a id="nav-brand" class="navbar-brand" href="<%= index_url %>">Cronut.io</a>
        </div>
        <!-- Navbar items that will collapse into a button w/ narrow widths -->
        <div class="collapse navbar-collapse" id="nav-bar">
          <ul id="top-nav-bar" class="nav navbar-nav">
            <li id="nav-gallery"><a href="<%= gallery_url %>">Gallery</a></li>
            <li id="nav-testimonials"><a href="<%= testimonials_url %>">Testimonials</a></li>
            <li id="nav-about"><a href="<%= about_url %>">About Us</a></li>
            <li id="nav-contact"><a href="<%= contact_url %>">Contact</a></li>
          </ul>
          <!-- Sign In Dropdown - still part of Navbar -->
            <% if signed_in? %>
            <div class="dropdown pull-right">
              <button 
                class="dropdown-toggle btn btn-primary user-drop-down"
                type="button"
                data-toggle="dropdown">
                <%= current_user.username %>
                <span class="caret"></span>
              </button>
              <ul class="dropdown-menu">
                <li><%= link_to "Profile", current_user %></li>
                <li><%= link_to "Sign Out", session_url, :method => :delete %></li>
              </ul>
            </div>
            <% else %>
            <div class="pull-right">
              <button 
                class="btn btn-primary"
                type="button"
                data-toggle="dropdown">
                Not Signed In?
                <span class="caret"></span>
              </button>
            <ul class="dropdown-menu">
              <!-- <li><a href="javascript:void(0)" id="contact-link"> -->
              <li><%= link_to "Sign In", "javascript:;", id: "sign-in-button" %></li>
              <li><%= link_to "Sign up", new_user_url %></li>
            </ul>
            </div>
            <% end %>
          
        </div>
      </div>
    </nav>
    
    <!-- Flash Notices -->
    <% if flash[:errors] %>
    <h3>Please fix the following errors:</h3>
    <ul>
      <% flash[:errors].each do |error| %>
      <li><%= error %></li>
      <% end %>
    </ul>
    <% end %>


    <!-- Need to wrap yielded view in a container div -->
    <div class="container">
      <%= yield %>
    </div>
    
    
    <div class="modal fade" id="signIn-modal">
      <div class="modal-dialog">
        <div class="modal-content">
          <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
            <h4 class="modal-title">Sign In</h4>
          </div>
          <div class="modal-body">
            <%= 
              render "users/form", 
              action: session_url, 
              message: "Log In" 
            %>
          </div>
          <div class="modal-footer">
            <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
            <button type="button" class="btn btn-primary">Save changes</button>
          </div>
        </div><!-- /.modal-content -->
      </div><!-- /.modal-dialog -->
    </div><!-- /.modal -->

  </body>
</html>

app/views/static_pages/about.html.erb
<!-- JumboTron -->
<div class="jumbotron">
  <h1>Yummy Cronuts</h1>
  <div class="row">
    <div class="col-xs-6">
      <p>Cupcake ipsum dolor sit amet topping candy. Sweet pie pastry gingerbread wafer candy canes sweet chupa chups donut. Candy canes macaroon sweet roll cookie pudding.
Tiramisu gummi bears bear claw icing icing gummies pastry muffin. Cake lemon drops tiramisu. Unerdwear.com pie tootsie roll. Donut sweet roll sweet macaroon chupa chups jujubes cheesecake chocolate cake.
Tart croissant muffin danish. Oat cake cupcake bear claw. Muffin halvah cookie sweet.</p>
    </div>
    
    <div class="col-xs-6">
      <p>Tiramisu gummi bears bear claw icing icing gummies pastry muffin. Cake lemon drops tiramisu. Unerdwear.com pie tootsie roll. Donut sweet roll sweet macaroon chupa chups jujubes cheesecake chocolate cake.
      </p>
      <p>Sweet pie pastry gingerbread wafer candy canes sweet chupa chups donut. Candy canes macaroon sweet roll cookie pudding.
      </p>  
    </div>
  
  </div>
</div><!-- class="jumbotron" -->

<div class="row text-center">
  <h1>Meet The Team</h1>
</div>

<div class="row">
  <div class="col-xs-3">
    <img src="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ6r6TkESr17au0vFYYCgiZODlhuk775jX8geVNqHOGQ8oTMQysIQ"
    class="img-circle img-responsive">
    <h2>Cinny Ginger</h2>
    <p>
      Froyo chocolate chip maple toppings ice cheesecake ice. Nut cake peppermint shortcake white chocolate mint almond, dessert cup maple. Snow cones nut toppings cone butterscotch froyo cone. Scoop soft serve, peppermint shortcake.
    </p>
  </div>
  <div class="col-xs-3">
    <img 
      src="http://i.huffpost.com/gen/1513856/thumbs/s-CRONUT-large.jpg"
      class="img-circle img-responsive">
      <h2>Choco Supes</h2>
      <p>
        Cheesecake nut cone coffee cone scoop chocolate chip vanilla, shortcake cake. Sherbet sundae cherry toppings pecan. Cookies and cream chunky sherbet flavour. Raspberry maple orange cup mint ice apple vanilla caramel, white chocolate raspberry.
      </p>
  </div>
  <div class="col-xs-3">
    <img      src="http://cdn.cstatic.net/images/gridfs/51b8c1d7f92ea10ff5018c3b/CronutsAdelaide.jpg"
      class="img-circle img-responsive">
      <h2>Blube Yogi</h2>
      <p>
        Chocolate chip chocolate chip mint cherry chocolate chip. Peanut butter, raspberry caramel, sorbet flavour chocolate scoop, caramel butterscotch. Chunky frozen, coffee ice, coffee pecan coffee scoop. Cherry froyo, maple, mocha scoop pecan peanut butter, mocha toppings sundae.
      </p>
  </div>
  <div class="col-xs-3">
    <img     src="http://finedininglovers.cdn.crosscast-system.com/BlogPost/l_5388_cronuts.jpg"
      class="img-circle img-responsive">
      <h2>Figgy Praline</h2>
      <p>
        Mint cherry mocha, blueberry coffee gelato, nut. Orange toppings chocolate chip sorbet cherry cup, peanut butter, mocha toppings scoop orange. Sorbet blueberry chocolate chip dessert chunky chunky blueberry. Maple marshmellow gelato, sundae sherbet cherry raspberry scoop, sherbet sherbet maple chunky.
      </p>
  </div>
</div>

<script>
$(function(){
  $('#nav-about').addClass("active");
});
</script>

app/views/static_pages/contact.html.erb
<h1>Contact Us</h1>

<div class="row">
  <div class="col-xs-6" id="contact-form">
    <div id="alert" role="alert" class="alert"></div>
    <form role="form">
      <div id="user-name-div" class="form-group">
        <label for="user_name">Name</label>
        <input 
          type="text"
          class="form-control"
          id="user_name">
      </div>
      <div id="user-message-div" class="form-group">
        <label for="user_message">Mesage</label>
        <input 
          type="text"
          class="form-control"
          id="user_message">
      </div>
      
      <input 
        type="button"
        id="submit-contact"
        class="btn btn-primary"
        value="Submit">
    </form>
  </div>
  

  <div class="col-xs-6">
    <table class="table table-striped table-bordered">
      <thead>
        <tr>
          <th>Employee Name</th>
          <th>Phone Number</th>
        </tr>
      </thead>
      <tbody>
        <tr>
          <td>Jessie</td>
          <td>555-555-5555</td>
        </tr>
        <tr>
          <td>Anna</td>
          <td>666-666-6666</td>
        </tr>
        <tr>
          <td>Jessie</td>
          <td>555-555-5555</td>
        </tr>
        <tr>
          <td>Anna</td>
          <td>666-666-6666</td>
        </tr>
        <tr>
          <td>Jessie</td>
          <td>555-555-5555</td>
        </tr>
        <tr>
          <td>Anna</td>
          <td>666-666-6666</td>
        </tr>
      </tbody>
    </table>
  </div>
  
</div><!-- class="row" -->
  
<script>
$(function(){
  $('#nav-contact').addClass("active");
});
</script>

app/views/static_pages/gallery.html.erb
<h1>Photo Gallery</h1>

app/views/static_pages/index.html.erb
<div id="cronut-carousel" class="carousel slide" data-ride="carousel">
  <ol class="carousel-indicators">
    <li data-target="#cronut-carousel" data-slide-to="0" class="active"></li>
    <li data-target="#cronut-carousel" data-slide-to="1"></li>
    <li data-target="#cronut-carousel" data-slide-to="2"></li>
  </ol>

  <div class="carousel-inner">
    <div class="item active">
      <%= image_tag("peach.jpg", height: '300', width: '100%', alt: "Peach") %>
    </div>
    <div class="item">
      <%= image_tag("vanilla.jpg", height: '300', width: '100%', alt: "Vanilla") %>
    </div>
    <div class="item">
      <%= image_tag("chocolate.jpg", height: '300', width: '100%', alt: "Chocolate") %>
    </div>
  </div>

  <!-- Controls -->
  <a class="left carousel-control" href="#cronut-carousel" role="button" data-slide="prev">
    <span class="glyphicon glyphicon-chevron-left"></span>
  </a>
  <a class="right carousel-control" href="#cronut-carousel" role="button" data-slide="next">
    <span class="glyphicon glyphicon-chevron-right"></span>
  </a>
</div>

<div class="row">
  <div class="col-xs-2 scroll-nav affix">
    <ul class="nav" role="tablist">
      <li><a href="#peach">Peach</a></li>
      <li><a href="#vanilla">Vanilla</a></li>
      <li><a href="#chocolate">Chocolate</a></li>
    </ul>
  </div>
  <div class="col-xs-7 col-xs-offset-2">
    <h2 id="peach">Peach</h2>
    <p>Oat cake gingerbread halvah candy canes I love cotton candy lemon drops. Topping I love dessert. Toffee liquorice sweet danish sugar plum I love fruitcake. Soufflé candy. Cupcake ipsum dolor sit amet candy gummies I love ice cream. Cupcake biscuit cotton candy donut cupcake. Brownie gummies cheesecake cake. Wafer carrot cake topping topping pastry chocolate cake. Lemon drops lemon drops gingerbread carrot cake applicake powder cotton candy cake jelly-o. Marshmallow oat cake fruitcake soufflé cotton candy sweet halvah. Liquorice pie I love cotton candy bonbon. Chocolate cake pudding sweet roll jelly beans wafer.
Fruitcake sweet roll I love bonbon dessert icing. Toffee chocolate lemon drops cookie. Marshmallow applicake applicake pie bear claw jelly beans wafer marshmallow. Gingerbread chupa chups halvah pie. Danish bear claw cotton candy topping. Gummies chupa chups sweet roll I love jelly-o chupa chups lemon drops I love tootsie roll. Brownie croissant candy canes I love cupcake.
Sugar plum tiramisu unerdwear.com apple pie croissant jujubes cake. Halvah marshmallow wafer cake marzipan pudding brownie croissant. Jelly-o cheesecake chupa chups. Dragée dessert brownie powder chocolate brownie. Muffin I love pudding chocolate cake jelly beans chocolate I love halvah dragée. Candy canes chocolate bar cupcake. Tiramisu I love I love oat cake unerdwear.com wafer jujubes croissant. Chupa chups dessert gingerbread candy cookie sugar plum tart lollipop. Donut topping croissant chocolate cake.
      <span 
        class="tool-tip" 
        data-toggle="tooltip"
        data-placement="top"
        title="muffin">canes bonbon muffin</span> pudding gummies. Cotton candy donut oat cake. I love liquorice marzipan jelly beans. I love I love I love wafer danish I love macaroon pudding. Unerdwear.com chocolate cake pudding. Bonbon tiramisu marzipan lemon drops chocolate bar tart sweet roll. I love brownie icing cookie
      <span 
        class="tool-tip"
        data-toggle="tooltip"
        data-placement="top"
        title="ginger">gingerbread</span> candy canes halvah jelly beans.
    </p>
    
    <h2 id="vanilla">Vanilla</h2>
    <p>Carrot cake soufflé cookie donut pudding. Wafer I love caramels. Dragée soufflé ice cream topping chocolate bar I love dragée. I love biscuit soufflé tart liquorice brownie caramels. Donut cotton candy tart. Cupcake cake sugar plum topping marshmallow cake cotton candy. Ice cream chocolate I love chocolate wafer. Fruitcake sweet roll I love bonbon dessert icing. Toffee chocolate lemon drops cookie. Marshmallow applicake applicake pie bear claw jelly beans wafer marshmallow. Gingerbread chupa chups halvah pie. Danish bear claw cotton candy topping. Gummies chupa chups sweet roll I love jelly-o chupa chups lemon drops I love tootsie roll. Brownie croissant candy canes I love cupcake.
Sugar plum tiramisu unerdwear.com apple pie croissant jujubes cake. Halvah marshmallow wafer cake marzipan pudding brownie croissant. Jelly-o cheesecake chupa chups. Dragée dessert brownie powder chocolate brownie. Muffin I love pudding chocolate cake jelly beans chocolate I love halvah dragée. Candy canes chocolate bar cupcake. Tiramisu I love I love oat cake unerdwear.com wafer jujubes croissant. Chupa chups dessert gingerbread candy cookie sugar plum tart lollipop. Donut topping croissant chocolate cake.
Dessert cookie sweet roll cotton candy powder. Gingerbread jelly-o soufflé toffee. Tiramisu macaroon I love cookie dragée bear claw candy bonbon. Bear claw toffee danish sweet roll. Cotton candy chocolate cake apple pie. Cake cookie dragée wafer.Carrot cake soufflé cookie donut pudding. Wafer I love caramels. Dragée soufflé ice cream topping chocolate bar I love dragée. I love biscuit soufflé tart liquorice brownie caramels. Donut cotton candy tart. Cupcake cake sugar plum topping marshmallow cake cotton candy. Ice cream chocolate I love chocolate wafer. Fruitcake sweet roll I love bonbon dessert icing. Toffee chocolate lemon drops cookie. Marshmallow applicake applicake pie bear claw jelly beans wafer marshmallow. Gingerbread chupa chups halvah pie. Danish bear claw cotton candy topping. Gummies chupa chups sweet roll I love jelly-o chupa chups lemon drops I love tootsie roll. Brownie croissant candy canes I love cupcake.
Sugar plum tiramisu unerdwear.com apple pie croissant jujubes cake. Halvah marshmallow wafer cake marzipan pudding brownie croissant. Jelly-o cheesecake chupa chups. Dragée dessert brownie powder chocolate brownie. Muffin I love pudding chocolate cake jelly beans chocolate I love halvah dragée. Candy canes chocolate bar cupcake. Tiramisu I love I love oat cake unerdwear.com wafer jujubes croissant. Chupa chups dessert gingerbread candy cookie sugar plum tart lollipop. Donut topping croissant chocolate cake.
Dessert cookie sweet roll cotton candy powder. Gingerbread jelly-o soufflé toffee. Tiramisu macaroon I love cookie dragée bear claw candy bonbon. Bear claw toffee danish sweet roll. Cotton candy chocolate cake apple pie. Cake cookie dragée wafer.

      <span 
        class="tool-tip"
        data-toggle="tooltip"
        data-placement="top"
        title="snaps">soufflé sesame snaps</span> tart unerdwear.com. Donut sweet cupcake cake. Liquorice powder jelly cookie jelly.
    </p>
    <h2 id="chocolate">Chocolate</h2>
    <p>Tiramisu gingerbread cotton candy apple pie macaroon. Carrot cake fruitcake gummi bears. Fruitcake lemon drops pudding. Sesame snaps oat cake donut. Carrot cake gingerbread I love bear claw jujubes dessert. Topping soufflé lemon drops brownie halvah. Jelly-o chocolate bar soufflé candy bear claw chupa chups sweet. 
      <span 
        class="tool-tip"
        data-toggle="tooltip"
        data-placement="top"
        title="Chupa!">Chupa chups</span> brownie brownie toffee. Candy canes soufflé cake. Marzipan cupcake toffee dessert tiramisu muffin jelly beans oat cake lollipop. Sugar plum tiramisu unerdwear.com apple pie croissant jujubes cake. Halvah marshmallow wafer cake marzipan pudding brownie croissant. Jelly-o cheesecake chupa chups. Dragée dessert brownie powder chocolate brownie. Muffin I love pudding chocolate cake jelly beans chocolate I love halvah dragée. Candy canes chocolate bar cupcake. Tiramisu I love I love oat cake unerdwear.com wafer jujubes croissant. Chupa chups dessert gingerbread candy cookie sugar plum tart lollipop. Donut topping croissant chocolate cake.
Dessert cookie sweet roll cotton candy powder. Gingerbread jelly-o soufflé toffee. Tiramisu macaroon I love cookie dragée bear claw candy bonbon. Bear claw toffee danish sweet roll. Cotton candy chocolate cake apple pie. Cake cookie dragée wafer.
Sweet topping I love I love. Tiramisu jujubes bonbon. Halvah dragée I love lollipop oat cake marshmallow croissant. Oat cake macaroon cookie cotton candy cookie pudding biscuit bonbon jelly beans. Gummies cheesecake unerdwear.com. Gingerbread halvah dessert biscuit. Sesame snaps biscuit croissant toffee liquorice lollipop. Sugar plum tiramisu unerdwear.com apple pie croissant jujubes cake. Halvah marshmallow wafer cake marzipan pudding brownie croissant. Jelly-o cheesecake chupa chups. Dragée dessert brownie powder chocolate brownie. Muffin I love pudding chocolate cake jelly beans chocolate I love halvah dragée. Candy canes chocolate bar cupcake. Tiramisu I love I love oat cake unerdwear.com wafer jujubes croissant. Chupa chups dessert gingerbread candy cookie sugar plum tart lollipop. Donut topping croissant chocolate cake.
Dessert cookie sweet roll cotton candy powder. Gingerbread jelly-o soufflé toffee. Tiramisu macaroon I love cookie dragée bear claw candy bonbon. Bear claw toffee danish sweet roll. Cotton candy chocolate cake apple pie. Cake cookie dragée wafer.

    </p>
  </div>
</div>

app/views/static_pages/testimonials.html.erb
<h1>User Testimonials</h1>

app/views/users/_form.html.erb
<form action="<%= action %>" method="post" role="form">
  <input
     name="authenticity_token"
     type="hidden"
     value="<%= form_authenticity_token %>">

  <div class="form-group">
    <label for="user_username">Username</label>
    <input
      class="form-control"
      id="user_username"
      name="user[username]"
      type="text">
  </div>

  <div class="form-group">
    <label for="user_password">Password</label>
    <input
      class="form-control"
      id="user_password"
      name="user[password]"
      type="password">
  </div>

  <button class="btn btn-primary"><%= message %></button>
</form>

app/views/users/new.html.erb
<div class="row">
  <div class="col-xs-4 col-xs-offset-1">
    <h1>Create User</h1>

        <%= render "form", action: users_url, message: "Sign Up" %>
  </div>
</div>

app/views/users/show.html.erb
<h1><%= @user.username %></h1>

<p>Hello, dear user!</p>